<a href="https://colab.research.google.com/github/JeeyeonKim00/TIL/blob/master/02_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
input_var = tf.Variable(initial_value=3)
with tf.GradientTape() as tape:
  result = tf.square(input_var)

  gradient = tape.gradient(result, input_var)

In [3]:
input_var

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [6]:
tf.constant(3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [9]:
input_const = tf.constant(3)

with tf.GradientTape() as tape:
  tape.watch(input_const)
  result = tf.square(input_const)
gradient = tape.gradient(result, input_square)

NameError: ignored

In [13]:
import numpy as np

num_sample_per_class = 1000
negative_samples = np.random.multivariate_normal(
    mean=[0,3],
    cov=[[1,0.5],[0.5,1]],
    size= num_sample_per_class
)

positive_samples = np.random.multivariate_normal(
      mean=[3,0],
      cov=[[1,0.5],[0.5,1]],
      size = num_sample_per_class
)
negative_samples

array([[ 1.08455827,  3.49893462],
       [-0.81476535,  3.31583866],
       [-1.69273209,  1.89835513],
       ...,
       [ 1.61250006,  4.00791847],
       [-0.23242453,  2.34129043],
       [ 1.91469227,  3.59932094]])

In [14]:
negative_samples.shape, positive_samples.shape

((1000, 2), (1000, 2))

In [15]:
inputs = np.vstack((negative_samples, positive_samples)).astype(np.float32)

In [18]:
inputs.shape

(2000, 2)

In [21]:
targets = np.vstack((np.zeros((num_sample_per_class,1),dtype='float32')
                    ,np.ones((num_sample_per_class,1),dtype='float32')))

In [24]:
targets.shape

(2000, 1)

In [25]:
inputs

array([[ 1.0845582 ,  3.4989345 ],
       [-0.81476533,  3.3158386 ],
       [-1.6927321 ,  1.8983551 ],
       ...,
       [ 1.6365747 , -0.44074243],
       [ 3.1480854 , -1.6844764 ],
       [ 3.3135538 , -0.39928624]], dtype=float32)

In [ ]:
import matplotlib.pyplot as plt

plt.scatter(inputs[:,0])

In [26]:
from tensorflow import keras

class SimpleDense(keras.layers.Layer):
  def __init__(self, units, activation=None):
    super().__init__()
    self.units = units
    self.activation = activation

  def build(self, input_shape):
    input_dim = input_shape[-1]
    self.W = self.add_weight(shape=(input_dim,self.units),
                             initializer = 'random_normal')
    self.b = self.add_weight(shape=(self.units),
                             initializer ='zeros')
  
  def call(self, inputs):
    y = tf.matmul(inputs, self.W) + self.b
    if self.activation is not None:
      y= self.activation(y)
    return y
    


In [33]:
# keras에서 Dense 층 만드릭

from tensorflow import keras

class SimpleDense(keras.layers.Layer):
  def __init__(self, units,activation=None):
    super().__init__()
    self.units = units
    self.activation = activation


  def build(self, input_shape):
    input_dim = input_shape[-1]
    self.W = self.add_weight(shape=(input_dim, self.units),
                             initializer ='random_normal')
    self.b = self.add_weight(shape=(self.units),
                             initializer ='zeros')
    

  def call(self, inputs):
    y= tf.matmul(inputs, self.W)+self.b
    if self.activation is not 'None':
      y= self.activation(y)
    return y

<>:22: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:22: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<ipython-input-33-1be35c4afff2>:22: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.activation is not 'None':


In [34]:
my_dense = SimpleDense(units=32, activation=tf.nn.relu)


In [35]:
input_tensor = tf.ones(shape=(2,784))
output_tensor = my_dense(input_tensor)

print(output_tensor.shape)

(2, 32)


In [36]:
from tensorflow.keras import models
from tensorflow.keras import layers

model = models.Sequential([
    layers.Dense(32, activation='relu'),
    layers.Dense(32)
])

In [38]:
model =keras.Sequential([keras.layers.Dense(1)])
model.compile(optimizer='rmsprop',
              loss='mean_squared_error',
              metrics=['accuracy'])

In [40]:
model.compile(optimizer = keras.optimizers.RMSprop(learning_rate = 1e-4),
              loss=keras.losses.MeanSquaredError(),
              metrics=[keras.metrics.BinaryAccuracy()])

In [41]:
history = model.fit(
    inputs,
    targets,
    epochs=5,
    batch_size=128
)

Epoch 1/5
16/16 [==============================] - 2s 3ms/step - loss: 10.6503 - binary_accuracy: 0.2505
Epoch 2/5
16/16 [==============================] - 0s 3ms/step - loss: 10.6155 - binary_accuracy: 0.2505
Epoch 3/5
16/16 [==============================] - 0s 3ms/step - loss: 10.5855 - binary_accuracy: 0.2500
Epoch 4/5
16/16 [==============================] - 0s 3ms/step - loss: 10.5560 - binary_accuracy: 0.2500
Epoch 5/5
16/16 [==============================] - 0s 3ms/step - loss: 10.5266 - binary_accuracy: 0.2500


In [46]:
history.history

{'loss': [10.650318145751953,
  10.61546516418457,
  10.585464477539062,
  10.55598258972168,
  10.526627540588379],
 'binary_accuracy': [0.25049999356269836,
  0.25049999356269836,
  0.25,
  0.25,
  0.25]}

In [ ]:
from tensorflow import keras


model = keras.Sequential([keras.layers.Dense(1)])
model.compile(optimizer=keras.optimizers.RMSprop(learning_rate=0.1),
              loss = keras.losses.MeanSquaredError(),
              metrics=[keras.metrics.BinaryAccuracy()])

indices_permutation = np.random.permutation(len( ))